version: '3'
services:
  app:
    build: .
    ports:
      - "3006:3000"
    volumes:
      - ./public:/app/public
      - ./assets:/app/assets
    depends_on:
      - node
    environment:
      - NODE_ENV=development
    command: npm start

  node:
    image: node:14
    volumes:
      - /app/node_modules
    working_dir: /app
    command: npm install